### ISSUE TITLE
ShapeConstraintLayout 内容布局变了

### ISSUE THREAD

**Issue by cjcj125125** [michaelxs/Android-CommonShapeViewGroup#2]

**Comment by cjcj125125** [comment]
再预览布局和ConstraintLayout布局的时候是没有问题的，但是用了你这个ShapeConstraintLayout 后布局内控件位置错乱了，求教

**Comment by michaelxs** [comment]
ShapeConstraintLayout本质上就是一个ConstraintLayout，你只需要按照ConstraintLayout的标准布局即可。
